### ISSUE TITLE
Contribution to PeakRDL uvm and pdf

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/RALBot-uvm#16]
I have used your project and added support to UVM to add coverage Sampling, which doesn't get generated by the RAL generated,  this is based on my DVCON paper I published. Also I have added support for generating pdf file from the input.  
I would like to contribute but the pull request has a lot of unrelated and side-tracked features too. I think it's best to have a call, where I'll present my work and then we can discuss how and what to contribute back. 

Let me know your thoughts over this.

**Comment by amykyta3** [comment]
Hi Muneeb,
I plan to significantly rewrite the UVM generator in the next version (v3.0). One of the changes I plan to incorporate in v3.0 is better alignment with the recommendations outlined in the UVM 1.2 users guide (#21) which includes better support for coverage sampling. I would be interested in understanding what you had in mind for this area.

If you want, please open a ticket to describe the specific changes. Since I plan to significantly rewrite this tool, I do not think a pull request would be particularly effective.

Alternatively we can coordinate something offline. My email is [removed]. Feel free to reach out to me there to coordinate.

**Comment by muneebullashariff** [comment]
I have sent the email for the call. Let's sync up.

**Comment by muneebullashariff** [comment]
Hello, 
Wanted to check if you would like to have a conversation in this regard?
